#!/bin/bash
#
# circonus-fq        Startup script for Circonus message queue
#
# chkconfig: - 82 12
# description: Circonus message queue
# processname: fqd
#
### BEGIN INIT INFO
# Provides: fqd
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: start and stop Circonus message queue
# Description: Circonus message queue
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog=fqd
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-60}
OPTIONS=""

start() {
        pushd /opt/circonus/var/lib/fq > /dev/null
        echo -n $"Starting $prog: "
        daemon --user=fq /opt/circonus/sbin/$prog $OPTIONS
        RETVAL=$?
        echo
        popd > /dev/null
        return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
    killproc -d ${STOP_TIMEOUT} /opt/circonus/sbin/$prog
    RETVAL=$?
    echo
    [ $RETVAL = 0 ]
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $prog
	RETVAL=$?
	;;
  restart)
	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=2
esac

exit $RETVAL
